"""add_user_email_and_field_updates

Revision ID: aac3b51f0995
Revises: 25eb5dc01613
Create Date: 2026-05-23 10:48:59.713186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac3b51f0995'
down_revision: Union[str, None] = '25eb5dc01613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
